### ISSUE TITLE
Exporting CSV for all errata times out

### ISSUE THREAD

**Issue by lwtchu** [openstax/bit#100]
### Description

**SCENARIO** _Briefly describe the issue._
When I select all errata and export the data as a CSV file, it times out.

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [x] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:**  larissa.chu@rice.edu
- **URL:**  https://openstax.org/django-admin/errata/errata/
- **Course number:**  N/A
- **Course type:**  N/A

- **Steps**
-Select all errata
-Click "Select all 7--- erratum"
-Drop down - Export as CSV file
-Hit GO!

----------------
**Environment:**

- **Instance:**
` [x] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ x ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [x] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
I need this for mah reportz.
----------------
**Images or Screenshots** (_attach below_)
![Screen Shot 2018-11-02 at 3.52.48 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/cd0e67fd-cb79-4e1f-a30a-c670d1955488)

**Comment by Malar-Natarajan** [comment]
@mwharrison Trying to export all errata still times out

![Screen Shot 2018-11-12 at 11.18.32 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/1c313593-4cdc-4f9a-b890-588263e5b339)

**Comment by mwharrison** [comment]
@Malar-Natarajan - I'm almost sure this is because the QA server does not have the same number of resources as production (I just verified that with Ryan). If it's okay with you, I'd like to get this on production and see if it works there?
It's already broken on production, so it' can't do anything but help. 😄

**Comment by lwtchu** [comment]
@mwharrison would it help with the csv file size if we deleted some fields? (marc told me the thing is just gettin too big)

**Comment by mwharrison** [comment]
@lwtchu - I don't think so, but maybe.
It would help more if we could archive some that don't need to be on the report. Are you always going to need all of them?

**Comment by lwtchu** [comment]
@mwharrison there's still a good amount (4138) of unarchived errata so it still breaks the tool. we can try the email way?

**Comment by mwharrison** [comment]
We're going to email the export to cmsupport@openstax.org
