### ISSUE TITLE
Twitter share button in the adoption form - additional questionnaire starts with "undefined an OpenStax textbook! "

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/bit#101]
### Description
Twitter share button in the adoption form - additional questionnaire starts with "undefined an OpenStax textbook! "

**SCENARIO** _Briefly describe the issue._
1. Submit an adoption form
2. Submit the additional questions and calculate cost saving 
3. CLick on the Twitter button to share the message.

The message in twitter is starting as " undefined an OpenStax textbook! "
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [X] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

![Screen Shot 2018-11-05 at 4.32.41 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/4d2e5cb9-21df-4882-ae02-67b380303774)
![Screen Shot 2018-11-05 at 4.32.55 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/513eb76e-f791-4565-a8fc-024e6372acaf)

**Comment by allisonhowell** [comment]
Maybe get rid of this option completely?

**Comment by gregfitch** [comment]
Verified on QA
