### ISSUE TITLE
custom license text is missing in the phone view of a book details page

### ISSUE THREAD

**Issue by gregfitch** [openstax/bit#103]
### Description

**SCENARIO** _Briefly describe the issue._

The custom license field text doesn't show up under the phone view book details. If the custom text isn't used, the license text shows in standard and narrow views.

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [X] ` N/A
- **Username:** 
- **URL:**  https://openstax.org/details/books/calculus-volume-2
- **Course number:**  
- **Course type:**  

- **Steps**

switch from full view to phone view
open 'Book details'
open 'Product details'

----------------
**Environment:**

- **Instance:**
` [X] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

the license image is there but the text is not

----------------
**Images or Screenshots** (_attach below_)

![screen shot 2018-11-08 at 10 19 33 am](https://user-images.githubusercontent.com/8904283/48212125-901c8380-e340-11e8-9433-aa90edc31de9.png)
![screen shot 2018-11-08 at 10 19 23 am](https://user-images.githubusercontent.com/8904283/48212126-901c8380-e340-11e8-81ef-652304291a37.png)

**Comment by Malar-Natarajan** [comment]
Verified in QA

**Comment by Malar-Natarajan** [comment]
Verified in staging
