### ISSUE TITLE
The drop down menu under the "Hi <Name>" does not lock long enough to use the menu options. ( not always)

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#109]
### Description

**SCENARIO** _Briefly describe the issue._

The drop-down menu under the "Hi Name" does not lock long enough to use the menu options. ( not always)
This is an issue when people use initials or super short names. 

This seems to happen only in Chrome in both normal and incognito mode.

- **Instance:**
` [ x] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ x] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge

----------------
**Images or Screenshots** (_attach below_)

**Comment by meeragovindaraju** [comment]
![2018-11-09_16-11-27.gif](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/67505845-1a83-4648-a5a9-c8d845bd2f73)

![Screen Shot 2018-11-09 at 3.43.47 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/28b3f2cf-97db-49fa-9de4-bfbe1878c0ae)

![2018-11-09_15-44-20 (1).png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/11e6f522-568a-48c6-a7a9-01b0e89fbd1b)

**Comment by RoyEJohnson** [comment]
Fix included with https://github.com/openstax/bit/issues/54

**Comment by Malar-Natarajan** [comment]
Verified in QA
