### ISSUE TITLE
SEO-Optimize H1 tags

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#11]
### Description
The following criteria should be met to optimize H1 tags: 
(a) There should be exactly one H1 per page. Many pages are missing the H1 (e.g. on book pages, should be book title)
(b) H1s should be unique
(c) The most competitive keywords should be represented in the H1
(d) 3-5 words ideal

### Acceptance
H1 tags have been added to all webpages.

**Comment by meeragovindaraju** [comment]
#Acceptance
H1 tags have been added to all webpages.

**Comment by meeragovindaraju** [comment]
Trello Card
https://trello.com/c/APmcN0kg/890-optimize-h1-tags

**Comment by RoyEJohnson** [comment]
Subjects page needs Page Description changed in the CMS. Currently has `h2` tag; should have `h1`.

**Comment by RoyEJohnson** [comment]
License has an `h1` embedded in its content block, but the editor does not allow you to set things to `h1`, so you need to be careful to preserve it.

**Comment by meeragovindaraju** [comment]
Code work is complete and released. Creating another issue for the non-code items remaining.

**Comment by allisonhowell** [comment]
@meeragovindaraju Did you create a separate issue for non-code work? If yes, can you please assign me? We can add to Q1 plan.
