### ISSUE TITLE
Resolve duplicate articles on press and blog pages - implement redirects & remove dups

### ISSUE THREAD

**Issue by laurenloh** [openstax/bit#117]
# Description
Some press releases are on both the blog and the press page with separate URLs. 301 redirect each blog URL to the duplicate on the press page.

[DevOps Trello card](https://trello.com/c/tvkybzOL)

# Acceptance Criteria
- Duplicate articles on the blog have been removed. 
- Blog URLs redirect to the duplicate on the press page. 

# Acceptance Tests

Verify redirects are working correctly. 

**title**: Redirect verification template  
**categories**: 
GIVEN a user   
WHEN they navigate to one of the six pages redirected from /blog/ to /press/  
THEN the user will be redirect to /press/

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [x] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [x] The solution is updated.

2-CODE
  - [x] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [x] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

**Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by allisonhowell** [comment]
@scb6 Here is list of duplicate articles on the press and blog pages. We need to redirect all of the blog urls to the press urls:

Blog: https://openstax.org/blog/openstax-textbooks-now-available-through-bookstore-digital-access-programs should be redirected to Press: https://openstax.org/press/openstax-textbooks-now-available-through-bookstore-digital-access-programs

Blog: https://openstax.org/blog/openstax-partners-katalyst-deliver-free-textbooks-poland should be redirected to Press: https://openstax.org/press/openstax-partners-katalyst-deliver-free-textbooks-poland

Blog: https://openstax.org/blog/openstax-partners-uk-open-textbooks should be redirected to Press: https://openstax.org/press/rice-university-based-openstax-partners-uk-open-textbooks

Blog: https://openstax.org/blog/nearly-15-million-college-students-use-free-textbooks should be redirected to Press: https://openstax.org/press/nearly-15-million-college-students-use-free-textbooks-school-year

Blog: https://openstax.org/blog/openstax-launches-personalized-learning-tool-college-courses should be redirected to Press: https://openstax.org/press/openstax-launches-personalized-learning-tool-college-courses

Once those redirects I will remove the duplicate articles from the blog.

**Comment by scb6** [comment]
https://github.com/openstax/oscms-deployment/pull/90

**Comment by Malar-Natarajan** [comment]
Verified in QA

**Comment by Malar-Natarajan** [comment]
Verified in Staging
