### ISSUE TITLE
SEO-Block form confirmation/thank-you pages

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#12]
### Description
Block form confirmation/thank-you pages in robots.txt for adoption, interest, giving, and any other form.

### Acceptance
Confirmation/thank-you pages for all forms have been blocked in robots.txt.

**Comment by meeragovindaraju** [comment]
Acceptance
Confirmation/thank-you pages for all forms have been blocked in robots.txt.

**Comment by meeragovindaraju** [comment]
##Block robots from indexing confirmation pages
https://github.com/openstax/os-webview/commit/2e4d713ba29956ac7d9ab715f949f02eef3cde0e

**Comment by meeragovindaraju** [comment]
### Add canonical tag for details pages #1241
https://github.com/openstax/os-webview/pull/1241

**Comment by meeragovindaraju** [comment]
Trello Card
https://trello.com/c/RWRpgMdP/900-block-form-confirmation-thank-you-pages

**Comment by RoyEJohnson** [comment]
This is already in production.

**Comment by allisonhowell** [comment]
@RoyEJohnson Can you tell me when this was put in production? This is for the SEO consultant and will help us with reporting.

**Comment by RoyEJohnson** [comment]
@allisonhowell It was merged on Sep 27, so should have been in the Oct 8 release.
