### ISSUE TITLE
SEO: Redirect from openstax.org// to openstax.org

### ISSUE THREAD

**Issue by laurenloh** [openstax/bit#123]
### Description
Create a 301 redirect from openstax.org// and to openstax.org

### Acceptance
openstax.org// redirects to openstax.org

### Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low

**Comment by allisonhowell** [comment]
FYI @CourtneyRay I created a card on the DevOps Change Request board here: https://trello.com/c/Bb7jJV0K/191-seo-redirect-from-openstaxorg-to-openstaxorg

**Comment by scb6** [comment]
https://github.com/openstax/oscms-deployment/pull/78

**Comment by meeragovindaraju** [comment]
Will be released by devops tonight. Archiving this card.
