### ISSUE TITLE
SEO: Redirect openstax.org/index.php to openstax.org

### ISSUE THREAD

**Issue by laurenloh** [openstax/bit#124]
### Description
Create a redirect from openstax.org/index.php to openstax.org

#### Discussion
This may be a standard thing to do for some development platforms, but we don't use PHP, and there is no reason for anyone ever to be directed to `index.php`.

### Acceptance
openstax.org/index.php redirects to openstax.org

### Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low

**Comment by scb6** [comment]
https://github.com/openstax/oscms-deployment/pull/77

**Comment by meeragovindaraju** [comment]
Will be released by Devops tonight. Archiving this card.
