### ISSUE TITLE
Add a "More Information Requested" resolution field to errata

### ISSUE THREAD

**Issue by marcjeannott** [openstax/bit#125]
### Description
Content Managers are receiving an influx of errata that are not specific enough to send along to our SMEs. We'd like a new resolution field that would tell the user to submit a new report with more information. Currently we mark these as "Not an error" which I think sends the wrong message to users who may actually have an error, but haven't reported it well enough. 

### Acceptance
If an errata was submitted without any detail, CMs would set the status as complete and the resolution field as "More Information Requested". The resolution notes would auto-populate with text like this:

"Thank you for the feedback. Unfortunately, our reviewers were unable to locate this error. Please submit a new report with additional information, such as a link to the relevant content on cnx.org, or a screenshot."

### Impact

* **Severity**: [x] High [ ] Medium  [ ] Low

**Comment by marcjeannott** [comment]
I've added @allisonhowell and @openstaxalina to get approval of the auto-generated text I drafted. Please feel free to edit it if you think it needs changed.

**Comment by openstaxalina** [comment]
@marcjeannott thank you!  I made a small change directly in your comment to the way webview is described.  I defer to @allisonhowell if she'd like to make any additional tweaks.

**Comment by allisonhowell** [comment]
@marcjeannott Here is my suggested language:

"Thank you for the feedback. Unfortunately, our reviewers were unable to locate this error. Please submit a new report with additional information, such as a link to the relevant content, or a screenshot."

I took out cnx.org because I think users may not realize that's where they are. What do you think?

**Comment by openstaxalina** [comment]
@allisonhowell I think that's fine; I was the one who had added cnx.org.  I agree that your language is cleaner.

**Comment by Malar-Natarajan** [comment]
@mwharrison 
Testing in QA. As per Acceptance criteria, the "Resolution Notes" should be populated with the text.

But the resolution notes field is not populated with the text in admin screen. Email is sent to the user with the text as expected. On clicking Track status in the email, the "Decision Details" field is empty for the user. Should this also populate with the text?

cc @marcjeannott if you want to look at this feature - cms-qa.openstax.org

![2018-12-10_16-31-57.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/b7c3a2f9-155a-4d1f-8fdb-9bffe4a757f4)

![Screen Shot 2018-12-10 at 4.32.45 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/a93d30e7-4630-4d01-b003-d73da018fbea)

**Comment by mwharrison** [comment]
@Malar-Natarajan - I totally missed that was supposed to happen. I will put up a PR, ASAP!

**Comment by Malar-Natarajan** [comment]
Verified in Staging
