### ISSUE TITLE
SEO-Add a 301 redirect from retired book pages to the current-edition page

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#13]
### Description
Add a 301 redirect from book pages of retired editions to the current-edition page for that book.

Below are the links to the 1e pages currently needing the redirect:
https://openstax.org/details/books/introduction-sociology
https://openstax.org/details/books/principles-economics
https://openstax.org/details/books/principles-macroeconomics
https://openstax.org/details/books/principles-microeconomics
https://openstax.org/details/books/principles-macroeconomics-ap-courses
https://openstax.org/details/books/principles-microeconomics-ap-courses

### Acceptance
Retired editions of book pages 301 redirect to the current-edition of book pages.

**Comment by meeragovindaraju** [comment]
Acceptance
Retired editions of book pages 301 redirect to the current-edition of book pages.

**Comment by meeragovindaraju** [comment]
Trello Card
https://trello.com/c/Gi78mw4G/905-add-a-301-redirect-from-retired-book-pages-to-the-current-edition-page

**Comment by scb6** [comment]
This is hand coded for old type install and merged for new type.  After QA deployments and verification, I can hand code to old style production.

**Comment by mwharrison** [comment]
This was completed
