### ISSUE TITLE
Bug: Security warning: an embedded <script> tag on another site requested protected JavaScript and related errors

### ISSUE THREAD

**Issue by jessicatelles** [openstax/bit#151]
@jessicatelles commented on [Thu Oct 25 2018](https://github.com/openstax/bit-backlog/issues/41)

Trello: https://trello.com/c/VwAS4gEL/519-bug-security-warning-an-embedded-script-tag-on-another-site-requested-protected-javascript-and-related-errors

Scenario
--

We got a ton of those emails on 08-24:

```
An ActionController::InvalidCrossOriginRequest occurred in terms#show:

  Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.
  lib/omniauth/strategies/custom_identity.rb:100:in `other_phase'
```

And other associated error emails caused by the same errors as above:

```
An AbstractController::DoubleRenderError occurred in terms#show:

  Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".
  lib/omniauth/strategies/custom_identity.rb:100:in `other_phase'
```

```
An AbstractController::DoubleRenderError occurred in exceptions#rescue_from:

  Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".
  lib/omniauth/strategies/custom_identity.rb:100:in `other_phase'
```

For the first error, just make sure not to send dev exception notification emails for them. For the second error, we have to fix the double render on those actions when the `ActionController::InvalidCrossOriginRequest` triggers.

To test the fixes, you will need to iframe accounts from a different domain.

Whatever you do, DON'T enable the cross-origin embedding.

Code
--
- [ ] Role Task @Trellouser --- olp:4,6,8 --- ar:0,?

---

@jessicatelles commented on [Thu Oct 25 2018](https://github.com/openstax/bit-backlog/issues/41#issuecomment-433093180)

Greg Fitch Oct 13, 2017 at 9:40 AM
BE tasks; no QA work

Allison Howell Sep 14, 2017 at 9:52 AM
@ Dantemss  can you clarify the problem for me? Suggested priority?

**Comment by RoyEJohnson** [comment]
This appears to be over a year old.
