### ISSUE TITLE
Rover page - outline missing in the tiles for instructor/student info section

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/bit#171]
### Description

**Bug** _Choose the title for the issue or pick the correct lable._
Rover page - outline missing in the tiles for instructor/student info section

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_
1. Go to Rover page - instructor/student info section
2. The border in the tiles are missing.

Refer screenshot for the Staging environment
https://drive.google.com/file/d/1VeJtO_nZk71T71dCjYRWQ3kkCgUd6LxI/view?usp=sharing

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [X] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X] ` Chrome ` [X] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by RoyEJohnson** [comment]
I think this is actually intentional. Have to review the design file.

**Comment by allisonhowell** [comment]
@RoyEJohnson It needs to be centered though. This isn't high priority - we can fix when we launch the second phase of this page.

**Comment by RoyEJohnson** [comment]
This is what was in the design. Do you want the card contents centered, but without borders?
![Screen Shot 2018-12-12 at 4.15.08 PM.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/9bbc5b88-5ac8-46d2-998d-6601ab3883e2)

**Comment by RoyEJohnson** [comment]
[https://app.zenhub.com/files/150612775/b30fad0a-1016-4502-96fa-ab0462373f73/download]
