### ISSUE TITLE
Change canonicals from http to https URLs

### ISSUE THREAD

**Issue by CourtneyRay** [openstax/bit#172]
### Description

**Bug** 

Currently, canonical URLs are set to the http:// version of our URLs. They should be set to the https:// versions of those same URLs (because we're also 301-redirecting from each http URL to the respective https version of that URL. We are giving Google conflicting information). 

For example, https://openstax.org/adoption?Calculus currently points to http://openstax.org/adoption as canonical. It should point to https://openstax.org/adoption 

A full list of current canonical tags to non-200 URLs is here: https://docs.google.com/spreadsheets/d/1zhRNV2J-_gnEwq21FwxYMGGw9wbwSV0H-_UE5HHV1zo/edit?usp=sharing 

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
Can/will negatively impact our search rankings because we are giving conflicting info to Google about which pages to display.
----------------
**Images or Screenshots** (_attach below_)

**Comment by allisonhowell** [comment]
@CourtneyRay the code freeze for the last release of the year is today, 12/7. We won't be able to get this done in time. The next release won't be until January 15. Will this be a problem? If yes, can you let me know and we'll discuss?

**Comment by CourtneyRay** [comment]
@allisonhowell it's not ideal to have the conflicting canonicals, but I don't think it should warrant a hot fix. That should be fine, I think.

**Comment by RoyEJohnson** [comment]
Fixed in https://github.com/openstax/os-webview/pull/1316 (attached to https://github.com/openstax/bit/issues/122)

**Comment by Malar-Natarajan** [comment]
Verified few pages randomly and looks good in QA
