### ISSUE TITLE
Implement unique meta descriptions on pages with duplicate/missing info

### ISSUE THREAD

**Issue by CourtneyRay** [openstax/bit#175]
### Description
Some of our pages are missing meta descriptions or have duplicate descriptions. Those URLs that need attention on meta titles and meta descriptions are listed in the below Google Spreadsheet with notes on what is needed.

https://docs.google.com/spreadsheets/d/1urcDx64C1nVYrA3_2f6x-nnl9Qm22jDtl6cV1HBuvlg/edit#gid=0

### Acceptance

All issues listed in the meta descriptions Google Doc have been resolved.
Each page has a unique, descriptive meta title and description (unless it points to another page as canonical - in which case, the meta title and description should match those of the canonical page).

### Impact

Unique meta descriptions help search results for those pages because they give both Google and users more information on which to distinguish them.

* **Severity**: [ ] High [x] Medium  [ ] Low

### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by allisonhowell** [comment]
Everything is complete except for the subjects page titles and descriptions, which we don't currently have a solution for. That card has been iceboxed and will be revisited once we look at the subjects page design again. I am moving this card to done since everything else is complete.
