### ISSUE TITLE
Comp Copy sending blank book instead of Micro Econ

### ISSUE THREAD

**Issue by denvergreene** [openstax/bit#177]
### Description

**SCENARIO** Comp copy requests are coming into SF missing a subject. This only seems to be happening for Micro Econ 2e. We found it by emailing the person asking. It might be the 2e needs to be left off when submitting?

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_
From the comp request form, just select Micro Econ 2e 

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [X] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by mwharrison** [comment]
@allisonhowell - Denver says this is kind of important.

**Comment by allisonhowell** [comment]
@denvergreene this has been fixed.
