### ISSUE TITLE
redirect /Rover-by-OpenStax to /rover-by-openstax

### ISSUE THREAD

**Issue by CourtneyRay** [openstax/bit#178]
### Description
openstax.org/Rover-by-OpenStax is used in marketing materials, but it does not land on the Rover page because of the caps.

openstax.org/Rover-by-OpenStax should redirect to openstax.org/rover-by-openstax

### Acceptance
openstax.org/Rover-by-OpenStax redirects to openstax.org/rover-by-openstax

### Impact
Customers trying to find out more about Rover from our brochures/marketing materials will receive a 404 

* **Severity**: [x] High [ ] Medium  [ ] Low

**Comment by scb6** [comment]
https://github.com/openstax/oscms-deployment/pull/84
