### ISSUE TITLE
Create form for submitting your testimonial on interactive map

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#181]
### Description

There is a place where faculty and students can submit their testimonial on the interactive map. We need to create a form for people to submit their testimonial with the following fields:

Name (Should be populated by their being logged in)
Role (also from being logged in)
Book adopted (maybe we can get this from their account, too)
Open field for testimonial

The testimonial should be added to the contact in Salesforce, but should not appear on the map until it has been approved by marcom. (Probably need a checkbox in Salesforce.)

**Comment by meeragovindaraju** [comment]
Trello card for Salesforce work: https://trello.com/c/PMYAELcf/552-testimonial-processing

**Comment by RoyEJohnson** [comment]
Since the link is in at the school level, and it requires login, you may wind up having to search again after login. Might consider moving it. School is pulled from account info, so the link doesn't need to be at that level.

**Comment by Malar-Natarajan** [comment]
Can be tested only in production since map is loaded in production to talk with salesforce
