### ISSUE TITLE
Add the Chegg e-reader as an option under "Get this book" on book details page

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#182]
### Description

OpenStax has agreed to display the Chegg e-reader as an option under "Get this book" on the book details page.

We will need an additional field in the CMS for the link to the e-reader. This will not be for every book, so we need the additional field to be optional.

We will need to display their icon next to the link.

The e-reader will be the last option on the list.

**Comment by mwharrison** [comment]
@RoyEJohnson - this is ready to be merged and move onto your plate.

**Comment by mwharrison** [comment]
@RoyEJohnson - PR is up!

**Comment by gregfitch** [comment]
Verified on QA
