### ISSUE TITLE
KD Support Rover by OpenStax launch

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#189]
# Description

OpenStax is partnering with Querium to offer an online homework solution for select OpenStax math titles. This work on this card has been identified as work that is essential to releasing Rover by OpenStax to our users. 

# Acceptance Criteria
- All child cards have been completed.

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
~~- [ ] If UX design is needed then the UX label is added~~
~~- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~~
~~- [ ] A high-level solution (development approach for the code change) is added to the issue~~
~~- [ ] If prototype code is generated, it is linked to the issue.~~
~~- [ ] If tech briefs are generated, they are linked to the issue.~~

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items.
- [x] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [x] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [x] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [x] If an issue is included in a product phase, then Release is selected.

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by allisonhowell** [comment]
@victoria-cooke Please attach the design in this card when you're ready.

**Comment by victoria-cooke** [comment]
@allisonhowell Here's the base layout I showed you yesterday. Once I finish the updated version, I'll attach that as well.

![20190108_bit_roverwebpage_vcooke_v1-00](https://user-images.githubusercontent.com/45772258/50836757-9b2f6800-131f-11e9-8a53-4a12b77e2d22.jpg)

**Comment by victoria-cooke** [comment]
[Rover.zip](https://github.com/openstax/bit/files/2743155/Rover.zip)
@allisonhowell @RoyEJohnson Here's the Rover package. We can talk more tomorrow if you guys are free.

**Comment by victoria-cooke** [comment]
[Rover.zip](https://github.com/openstax/bit/files/2747025/Rover.zip)
@allisonhowell @RoyEJohnson Updated Rover files
