### ISSUE TITLE
SEO-Evaluate all soft 404s

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#2]
### Description
Evaluate all soft 404s - for links that are actually broken or unavailable, return a 404 status.

### Acceptance
A 404 status is added to all broken/unavailable soft 404s.

**Comment by meeragovindaraju** [comment]
Trello Card
https://trello.com/c/42OwQBHp/883-evaluate-all-soft-404s

**Comment by scb6** [comment]
I am unclear if this is a DevOps task or if this evaluation will take place outside of the code.

**Comment by CourtneyRay** [comment]
Allison, here is a list of soft 404s that need a 301 redirect where possible, or a 404 when not. https://docs.google.com/spreadsheets/d/10SAVQHx1WLrW2sPgoT6cztCIY3oB99iHc0GMnDtiOGI/edit#gid=0 

<blockquote><div><strong><a href="https://docs.google.com/spreadsheets/d/10SAVQHx1WLrW2sPgoT6cztCIY3oB99iHc0GMnDtiOGI/edit#gid=0">Google Sheets - create and edit spreadsheets online, for free.</a></strong></div><div>Create a new spreadsheet and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Sheets to edit Excel files. Free from Google.</div></blockquote>

**Comment by CourtneyRay** [comment]
Note - this should be the same task as https://app.zenhub.com/workspaces/openstax-bit-5bacfe3f4b5806bc2bea3764/issues/openstax/bit/119

We should create 301s for all soft 404s if possible (rather than returning a 404 status).

**Comment by BruceP99166** [comment]
Deprecated per Courtney's comment above.
