### ISSUE TITLE
Duplicate articles on press and blog - Identify the duplicates

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#204]

**Comment by allisonhowell** [comment]
@laurenloh Can you please create a list of articles that appear on both the press page and in the blog? You can list them here.

**Comment by laurenloh** [comment]
- OpenStax textbooks now available through bookstore digital access programs
- OpenStax partners with Katalyst to deliver free textbooks to Poland 
- OpenStax partners with UK Open Textbooks
- Nearly 1.5 million college students to use free textbooks this school year 
- OpenStax launches personalized learning tool for college courses
