### ISSUE TITLE
Google API deprecation

### ISSUE THREAD

**Issue by mwharrison** [openstax/bit#205]
# Description
We need to explore the ramifications of the deprecated Google+ auth api to accounts.

[sunsetting consumer Google+](https://github.com/jaredhanson/passport-google-oauth2/issues/50#issuecomment-449176111)
> Note: If you see calls to people.get, these can be the result of using the Google+ Sign-In feature in your application, which is now fully deprecated and is being shut down. Developers should migrate from the Google+ Sign-In feature to the more comprehensive Google Sign-in authentication system.

[integrating Google Sign-In](https://developers.google.com/identity/sign-in/web/sign-in)

# Acceptance Criteria

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: 
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

**Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by allisonhowell** [comment]
@mwharrison Any update on this card?

**Comment by mwharrison** [comment]
@allisonhowell 
I just pinged JP to get access to the Google+ dashboard. Until then, here is what I have found:

Looking through the accounts code, I see we are using google_oauth2, not the Google+ APIs (but I’m not sure if they are different - hoping logging in will provide more details).

I searched for the specific method it says we are using: https://github.com/openstax/accounts/search?q=plus.people.getOpenIdConnect&unscoped_q=plus.people.getOpenIdConnect

As well as read through any code using the term ‘google’: https://github.com/openstax/accounts/search?q=google&unscoped_q=google

**Comment by RoyEJohnson** [comment]
I modified the description with some information about the Google+ API sunset and the recommended Google Sign-In. If we are using oauth2, that is Google Sign-in, which is still supported. It looks like this card may be a non-issue.

**Comment by allisonhowell** [comment]
It sounds like we can probably close this issue. @mwharrison did you find anything pertinent from the Google+ dashboard, or can we close?
