### ISSUE TITLE
Faculty Verification/Adoption form multiples

### ISSUE THREAD

**Issue by denvergreene** [openstax/bit#208]
### Description

When fac v and adoption forms are filled out, leads are created in SF. If they indicate 5 books, then 5 leads are sent. If 5 leads are sent then 5 emails are sent. No one wants that.

What we would like to happen instead is for the first lead that is sent to have a checkbox marked false, but all other leads will be marked true. Then if true, will not send email. Doing it this way seems better for the long run automation, so we don't have to add this to all other lead forms.

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by meeragovindaraju** [comment]
Duplicate card
