### ISSUE TITLE
[OSWeb] FE: Implement CloudFront header forwarding and caching

### ISSUE THREAD

**Issue by laurenloh** [openstax/bit#212]
# Description
Enumerate the client headers that the backend servers use and which of those change the response from backend servers, so that CloudFront will cache out content effectively.

Story: https://docs.google.com/document/d/1UrhAptBawdqpQYyf7K6eHV6W-B7Pr22o9tNJxXld11w/edit#heading=h.cj10fzg4ref4

For Unified Reading Experience

# Acceptance Criteria

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [ ] High-level natural language acceptance tests are complete
~~- [ ] If UX design is needed then the UX label is added~~
~~- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~~
~~- [ ] A high-level solution (development approach for the code change) is added to the issue~~
~~- [ ] If prototype code is generated, it is linked to the issue.~~
~~- [ ] If tech briefs are generated, they are linked to the issue.~~

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items.
- [x] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [x] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [x] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
~~- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.~~
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

**Comment by RoyEJohnson** [comment]
The FE uses `{credentials: 'include'}` when fetching from the CMS (it causes cookies to be included),
I think that is the only setting that affects request headers. Typical request headers look like
```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: optimizelySegments=%7B%7D; optimizelyBuckets=%7B%7D; optimizelyEndUserId=oeu1511907708721r0.42386727122820145; _ga=GA1.2.300309143.1511907709; visitor_id218812=101362000; visitor_id218812-hash=79ccc6e399d06b4f356292e140997b95c7ad5b07d2cdc8d0482ad0108c3b6c28f52402a601c1d3317e613a9ee3d23550a24e0a00; csrftoken=A8Bxdj4tF84zOuroaWiSThKyNYvnzUWJH6YHwLOAmiWhIVZUEZUUtWsvcFCAJcEe; _gid=GA1.2.334981628.1548689172; ox=UUl6RXhvL1kyc3ZRNklUSXRnM1JMbS9qOUVxMlFsVHdIWU00TGt4NzY4N3g3Smt2VjJueERPY2VlRlE4YTlySjRVSjJBMWcycWpFcFVreUtXTFNIOFhiN2ZCeWdLR2cveUZlM0s4akM4aVUvUHpZOTMraldSYkZWTWMvTjhjd1JTRTduMitzRlUxMUpGLzlrSUJjR0xGMSs2T0d0S2k2cjlvTndrTDBKbnJEcUFrZng5T1RQbGE1bjNCQnk3a2ZSTFhxckRUZ1FxYThSakFsdDRnVjY5OVBxV3NMOVVrL2dDOEYxMDVqMkxMcU9QL0Z0Z0UxSHlDVnVDRDh0NEtwS2ZhZTFpMmFqZk9QcDVZbTFVS1RtKzdFL0pnZ2xPVHQ0VUVvNTVKRk8vdVRHRDhFbTR1c1BhajErN2xVdnREbStQcWtQR1ArcmUwQkpuSGlWSlRsWGJ5STN4WEMrd1NzZnNIUjdrVGlnWXZuTHl2TXdub0VwakFuZGJERkkvK29JYmtNOTZXYm1LUUxHRWdOMVFQMzNJN2lTS3Y3M3VwQlkrUE9lTFYxTUlMSlh2dk5wcTRNeE83c0d5elBTRG12SHduUGtRRXdQdHBMZXBwZkdEVXUvZGV1VVFxZjdxbTdJa2pmVXRSenZqQ009LS1yWEE0cEdydkI4YXJGZTJwamFOYitBPT0%3D--dac80c79e306a808c71e9c1289deadf7b704aa5b; _gat=1
Host: cms-dev.openstax.org
Pragma: no-cache
Referer: https://cms-dev.openstax.org/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
```

**Comment by allisonhowell** [comment]
@RoyEJohnson Have you confirmed if there is any other work needed on this card or is this sufficient?
