### ISSUE TITLE
Bug: Regression on errata form in CMS

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#22]
### SCENARIO
 An extra "OpenStax Book" field is now showing up in the errata tool edit form.

Steps to Reproduce the issue: Who, Where and How?

Product:
[ ] Accounts [ ] BigLearn
[ ] Exercises [ ] CNX
[ ] Payments [ ] Tutor
[ ] Highlight [ x] Web

User Type:
[x ] Admin [ ] Content/QA
[ ] Student [ ] Teacher
[ ] N/A

Username: ryan.s.stickney@gmail.com

URL: https://openstax.org/django-admin/errata/errata/6873/change/?_changelist_filters=status__exact%3DNew

### Acceptance 
edit any erratum with the tool

### Possible impact on a User:

extra step every time an errata report is edited

**Comment by meeragovindaraju** [comment]
<img width="505" alt="screen_shot_2018-09-11_at_9 05 00_am" src="https://user-images.githubusercontent.com/33066187/46365110-566ba500-c63d-11e8-867b-157f1f150cee.png">

**Comment by meeragovindaraju** [comment]
Trello Card
https://trello.com/c/wEIwpn87/917-bug-regression-on-errata-form-in-cms

**Comment by Malar-Natarajan** [comment]
Verified in QA
