### ISSUE TITLE
the Give form does not load

### ISSUE THREAD

**Issue by gregfitch** [openstax/bit#239]
### Description

**SCENARIO** _Briefly describe the issue._

The give form doesn't load; clicking `donate!` doesn't do anything.

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [X] ` N/A
- **Username:** 
- **URL:**  https://cms-qa.openstax.org/give
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by meeragovindaraju** [comment]
https://github.com/openstax/os-webview/pull/1322

**Comment by Malar-Natarajan** [comment]
Verified in Staging
