### ISSUE TITLE
Add roles to faculty verification form leads

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#24]
# Description
Currently, when leads come into Salesforce via the faculty verification form, the role does not come through.

# Solution
Need to add Role__c to the list of fields pushed to Salesforce (with a value of "Faculty"). That means OpenStax::Salesforce::Remote::Lead would need to take that additional parameter. That is in a separate gem: https://github.com/openstax/openstax_salesforce/blob/master/lib/openstax/salesforce/remote/lead.rb

For development, you can use set the gem to use a path to a locally modified gemfile

# Acceptance Criteria
The role comes in on the lead when a user fills out the faculty verification form.

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: 
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

**Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by meeragovindaraju** [comment]
Trello Card
https://trello.com/c/cOPmkWIK/804-add-roles-to-faculty-verification-form-leads-copy-in-zenhub

**Comment by Malar-Natarajan** [comment]
@RoyEJohnson 
FV leads are not displayed in sandbox. So unable to test this card

**Comment by RoyEJohnson** [comment]
The PR for this has not been merged. Dev Verify is before Code Done.

**Comment by Malar-Natarajan** [comment]
@RoyEJohnson 
The Role field in salesforce sandbox is still blank. I did a redeploy in QA with 393a1f405b804af5a74318b785a3976c24ab556e

**Comment by gregfitch** [comment]
SF seems to want an exact match (eg 'Adjunct Faculty' instead of 'adjunct')

![Screen Shot 2019-01-02 at 2.31.40 PM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/b2b1a462-449e-407d-aebb-dd6798a22e3e)

**Comment by allisonhowell** [comment]
Roles are coming, but adjunct faculty needs to be corrected. Closing this issue and creating a new one for Adjunct.
