### ISSUE TITLE
Cannot submit the instructor sign up form if any books are set as 'Recommending the book...'

### ISSUE THREAD

**Issue by gregfitch** [openstax/bit#242]
### Description

**SCENARIO** _Briefly describe the issue._

If an instructor trying to sign up for an account and select `'Recommending the book – my students buy a different book'`, they won't be able to submit the form. No errors occur so the instructor doesn't see anything.

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [X] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  https://accounts.openstax.org/signup
- **Course number:**  
- **Course type:**  

- **Steps**

Go to Accounts
sign up for an account
select Instructor
verify an email
set and verify a password
fill out the personal information
select `Fully adopted and using it as the primary textbook`
click Next
select a book
select 'Recommending the book – my students buy a different book'
enter a number of students
check 'I agree to the Terms...'
try to Create Account

----------------
**Environment:**

- **Instance:**
` [X] ` production ` [X] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

Cannot submit the form

----------------
**Images or Screenshots** (_attach below_)

https://drive.google.com/file/d/13AWDUJlhAZlp_eCV0Dde2Z2qKv0cYjiP/view?usp=sharing

**Comment by RoyEJohnson** [comment]
This is made moot by reverting the new faculty verification form.
