### ISSUE TITLE
For "Adjunct faculty" role, the FV form does not have the questions about adoption/interest and student estimate, So the salesforce fields are marked as "Not using" and "30". This behavior is incorrect 

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/bit#245]
### Description
For "Adjunct faculty" role, the FV form does not have the questions about adoption/interest and student estimate, So the salesforce fields are marked as "Not using" and "30". This behavior is incorrect 

**SCENARIO** 
For "Adjunct faculty" role, the FV form does not have the questions about adoption/interest and student estimate, So the salesforce fields are marked as "Not using" and "30". This behavior is incorrect 

Need to get the expected result from @allisonhowell 

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by allisonhowell** [comment]
@RoyEJohnson should this be moved to dev verify column?

**Comment by Malar-Natarajan** [comment]
Verified in QA.
Adjunct faculty behaves the same was as a Faculty
