### ISSUE TITLE
Since 1/25, CMS throws server error 500 inconsistently

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/bit#248]
### Description
When a user tries to login to the CMS, a 500 error is thrown with the following error:
`AuthAlreadyAssociated: This openstax account is already in use.`

This has happened with old accounts as well as newly created accounts.
When retrying in an incognito browser, the user is able to login.

No pattern has been found as to why this is happening.

**SCENARIO** 
I have been getting server error 500 intermittently in cms-qa/oscms-staging in the following cases:
1. clicking SUbmit button in the final step of new account signup 
2. clicking Login button while signing in as existing users

Retrying in a new browser version solves the issue. I encountered this issue these many times:
1. 1/31 - around 3.00 pm - chrome - QA
2. 1/31 - around 11.00 am - QA
3. one customer reported on 1/30
4. 1/30 - around 2.19 pm - QA - safari
5. 1/25 - once
6. 1/28 - once
7. 2/5 - once around 3.50 pm - chrome - QA 

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by mwharrison** [comment]
This should be fixed by https://app.zenhub.com/workspaces/openstax-bit-5bacfe3f4b5806bc2bea3764/issues/openstax/bit/253

I can't attach one PR to two cards, so I am making a comment.

cc/ @Malar-Natarajan

**Comment by Malar-Natarajan** [comment]
@mwharrison 
I just got a server 500 error while trying to login cms-qa with mn45+001@rice.edu on hitting submit button after entering the password. I think the wagtail upgrade doesn't necessarily resolve this server error issue

![Screen Shot 2019-02-19 at 4.24.12 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/61423981-4b86-4473-b073-db392091a638)

**Comment by mwharrison** [comment]
Closing #246 and working from this card instead.

**Comment by Malar-Natarajan** [comment]
So far no error in QA. Moving to regression and will be checking with regression testing

**Comment by Malar-Natarajan** [comment]
No errors logged after code freeze. Assuming this issue is fixed
