### ISSUE TITLE
Change Authorization screen in Accounts for SSO with Rover

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#260]
# Description
When a user logs into Rover for the first time with their OpenStax account, a screen that is hard to read is presented. We need to change the copy as well as the color contrast so that users can read it. 

# Acceptance Criteria
- The copy on the attached screenshot is changed from gray to white.
- The copy is changed to: "Do you authorize Rover by OpenStax to use your OpenStax account?"
- If possible, the "Authorize" and "Deny" buttons are made smaller, per our pattern library.
- If possible, the copy is centered. 

# Impact
All Rover by OpenStax users 

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
~~- [ ] If UX design is needed then the UX label is added~~
~~- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~~
~~- [ ] A high-level solution (development approach for the code change) is added to the issue~~
~~- [ ] If prototype code is generated, it is linked to the issue.~~
~~- [ ] If tech briefs are generated, they are linked to the issue.~~

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items.
- [x] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [x] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [x] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  ~~- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.~~
  - [ ] Distilled acceptance tests are added to the issue.
  ~~- [ ] Automated testing criteria are added to issue.~~
  ~~- [ ] The solution is updated.~~

2-CODE
  ~~- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.~~
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
 
4A-UX REVIEW
 ~~- [ ] The pull request is merged into master, and the change branch is deleted.~~

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

**Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by allisonhowell** [comment]
@mwharrison I thought I made this issue a long time ago! Are the changes minor enough to make the Feb. 15 code freeze? Note that two design elements are optional.

**Comment by allisonhowell** [comment]
![oauth-allow.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/2fe2e890-22d7-4308-965c-25bd3d410418)

**Comment by RoyEJohnson** [comment]
@allisonhowell This is used for "untrusted" apps. Is it the case that we want to treat Rover as an untrusted app? Or is the real fix to go into Accounts and mark it as trusted?

**Comment by allisonhowell** [comment]
That's a great point @RoyEJohnson. I think it should be marked as trusted. Is that okay with you @mwharrison?

**Comment by mwharrison** [comment]
I think if this is supposed to look like it’s seamlessly part of OpenStax - it should be marked as trusted and just not show this screen. It’s fine with me.

**Comment by allisonhowell** [comment]
Verified in Rover sign in flow that this screen is gone.
