### ISSUE TITLE
Allow books to be in two categories on the Subjects page on openstax.org

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#261]
### Description
Right now, books can only be under one subject area, Business, Math, Science, Humanities...Business Statistics falls into both the math and business categories. We need to allow for the book to be surfaced under both subject areas.

### Acceptance
- Business Statistics is listed under both Math and Business subject areas on openstax.org. 

### Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low

**Comment by RoyEJohnson** [comment]
Is there going to be a separate card for the front end work for this @allisonhowell ?

**Comment by allisonhowell** [comment]
@RoyEJohnson I can make one - I'm still not used to our new two/three cards for every change request!

**Comment by RoyEJohnson** [comment]
Oops: Books get stuck into AP multiple times.

**Comment by Malar-Natarajan** [comment]
Verified in QA

**Comment by Malar-Natarajan** [comment]
Verified in staging
