### ISSUE TITLE
Make spring re-engage page editable in the CMS 

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#266]
# Description 
Roy has built a beautiful spring re-engage web page, now we need to be able to edit the copy in the CMS.

# Acceptance
The spring re-engage web page is editable in the CMS.

**Comment by Malar-Natarajan** [comment]
https://cms-qa.openstax.org/admin/pages/300/edit/

**Comment by Malar-Natarajan** [comment]
Verified the page in QA. But since the FE is not linked to cms for this campaign we cannot test this time
