### ISSUE TITLE
Spacing not working correctly on blog posts

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#30]
### SCENARIO 
Spacing is wonky on blog posts. Spaces created in a blog entry in Wagtail are not reflected in the published post.

### Proposed solution
Add the HTML button back to the editor

**Comment by meeragovindaraju** [comment]
Trello Card
https://trello.com/c/GmgmVZT7/754-bug-spacing-not-working-correctly-on-blog-posts

**Comment by meeragovindaraju** [comment]
![screen_shot_2018-03-30_at_10 17 25_am](https://user-images.githubusercontent.com/33066187/46430459-9c446e00-c70e-11e8-8bbc-1bf738374013.png)
![screen_shot_2018-03-30_at_10 17 19_am](https://user-images.githubusercontent.com/33066187/46430466-a23a4f00-c70e-11e8-9897-82905e473301.png)

**Comment by RoyEJohnson** [comment]
Directed Courtney to the new-line button in the controls, and that works.
