### ISSUE TITLE
Change "Other" account flow

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#44]
### Description
Currently, when a user create an "other" account, they are taken through the faculty verification process because it's assumed that they are part of a school or university and need access to resources, but they are not teaching faculty. "Other" is meant to encompass any other role at a university besides faculty or instructor. 

This can be confusing because many of our users want to create an account to submit errata, but they are not an instructor or a student. Since our books can be used by anyone at any time, we should allow for users not affiliated with a school to create an account and submit errata. 

We don't want to take away the faculty verification option for other roles at a school or university, however, so we should make the "Other" account have an optional faculty verification process. That way users not affiliated with a school as well as users with non-instructor/faculty roles at schools can create an "other" account and get what they're looking for. 

### Acceptance
- A user can create an "Other" account without having to go through the faculty verification process.
- A user has the option to get faculty verified when they create an "Other" account.

**Comment by meeragovindaraju** [comment]
Trello Card
https://trello.com/c/6KTDEwmm/944-change-other-account-flow

**Comment by mwharrison** [comment]
Pinged @Dantemss today about reviewing the PR.

**Comment by allisonhowell** [comment]
@mwharrison do you think there is anyone else who can review? Dante will be out through the end of the year.

**Comment by mwharrison** [comment]
@allisonhowell - I'll check with JP
