### ISSUE TITLE
Put additional questions/text back on adoption/interest forms

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#48]
### Description
Before putting up the option to take the unicorn survey on the confirmation page of the adoption/interest forms, we had additional questions and text on the confirmation page. We need to add that back now that the unicorn surveys have been taken down. 

### Acceptance
The old questions/confirmation page text has been added back to the adoption/interest forms.

**Comment by meeragovindaraju** [comment]
https://trello.com/c/gqkQHGFO/914-put-additional-questions-text-back-on-adoption-interest-forms

**Comment by Malar-Natarajan** [comment]
@RoyEJohnson @allisonhowell 
I submitted interest form and do not see any change. Is this the expected confirmation page

![Screen Shot 2018-10-29 at 4.38.41 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/f8f6bf00-69ee-424e-9172-b183d3c2e0cb)

**Comment by RoyEJohnson** [comment]
Interest did not have additional questions, only adoption did.

**Comment by Malar-Natarajan** [comment]
Verified on Qa
