### ISSUE TITLE
Bug: Adoption and interest forms showing old-edition book covers

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#49]
**SCENARIO** 
Adoption and interest form show covers for old books because the Salesforce book list does not distinguish between editions and uses the data from the first entry for (say) Biology that comes from the CMS. Filter out entries whose book_state is not "live" to avoid using obsolete information.

**Comment by meeragovindaraju** [comment]
https://trello.com/c/U6eyxEtG/925-bug-template

**Comment by meeragovindaraju** [comment]
https://app.zenhub.com/workspace/o/openstax/os-webview/issues/1252

**Comment by Malar-Natarajan** [comment]
Verified in QA
