### ISSUE TITLE
OSW2.refresh.19 Add search function to OSWeb

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#50]
#Description
As OpenStax, we want to add a search to OSWeb so that our users can easily find the information they are looking for.

#Acceptance
There is a search bar on OSWeb where users can search for specific content.  

#Epic Doc
https://docs.google.com/document/d/1b843t28mMNmnU8LHcDM65nxh1V5QYeB9NJF98ZGT258/edit#heading=h.w4jnctd4w7zu 

#Design documentation

Invision link:
https://invis.io/7DFXEXVGH5T#/280178624_Blog_Search_1-0_-_Home_-

Zeplin link:
https://zpl.io/a7Z4klR

**Comment by meeragovindaraju** [comment]
https://trello.com/c/2sHkiPUN/676-osw2refresh19-add-search-function-to-osweb

**Comment by allisonhowell** [comment]
This is a Unicorn/BIT joint KD and is, for now, living under Unicorn. Therefore I'm closing.
