### ISSUE TITLE
Build Rover by OpenStax web page on OpenStax.org

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#56]
### Description

As an OpenStax math adopter, I want to learn more about Rover by OpenStax and be able to sign up for more information so that I can make the best online homework choice for myself and my students. 

I should be able to:

- Read more about the product and understand the key value propositions for faculty and students
- Learn the cost of Rover
- See which books are supported
- Sign up for more information
- Sign up for a webinar

###Acceptance
There is a page on OpenStax.org that gives the following information:

- Read more about the product and understand the key value propositions for faculty and students
- Learn the cost of Rover
- See which books are supported
- Sign up for more information
- Sign up for a webinar

The page lives under the "Technology" tab on OpenStax.org. 

###Epic Doc
https://docs.google.com/document/d/1y4ygCvTDQRwpxPvpAwoOVMZN2eD3UPtukK8fHDsGp7o/edit?ts=5bbbc573#heading=h.wuc3pn1ckk21

**Comment by Malar-Natarajan** [comment]
@allisonhowell
the card acceptance and epic doc says that phase 1 Rover will show the books supported. Where in the page can I verify the books supported?

@RoyEJohnson 
The "interested in rover" check box is not checked for the Rover lead.

**Comment by Malar-Natarajan** [comment]
The subjects are mentioned in one of the tiles. And the checkbox in salesforce lead is fixed with latest PR merge
