### ISSUE TITLE
Bug: No body preview is shown on pinned blog if piece begins with a heading

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#59]
### Description
If a blog post begins with a heading, no content preview is shown on openstax.org/blog when that piece is pinned. See screenshot.

The pinned post should feature the first set of text in <p> tags.

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by meeragovindaraju** [comment]
![image.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/36a906e1-9265-4a12-afed-e727a25ff1de)

![image.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/0d4407aa-095d-4c0e-bec7-96c12e9a059c)

**Comment by Malar-Natarajan** [comment]
Verified in QA
