### ISSUE TITLE
Add hover text for CreatorFest resources

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#63]
### Description

Currently CMs can put the CreatorFest logo on a resource in the CMS, but the page or card lacks explanation of what the logo means and why it's on there. We should add hover text over those cards with an explanation of what CreatorFest is. 

### Acceptance

There is hover text over cards on the book details page marked as CreatorFest resources.

**Comment by RoyEJohnson** [comment]
This change was included in the change out Creator Fest logo PR.

**Comment by Malar-Natarajan** [comment]
Verified in QA
