### ISSUE TITLE
Change out Creator Fest logo

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#67]
### Description

There has been a change to the CreatorFest logo that we currently have on the cards marked as CreatorFest resources. We need to switch it out with the attached logo. ![badge.png]![badge.svg](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/45f1baee-d06a-45ea-b866-b2881c85e20b)

**Comment by Malar-Natarajan** [comment]
Verified on QA
