### ISSUE TITLE
Create optional links on Current Projects on the research page

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#69]
### Description
The current projects tiles on the research page seem like they may link somewhere, but they don't. We are working on blog posts for each of the projects, so we should have an option to link as those are ready.

### Acceptance
There is an optional field in the CMS to add a link to the current projects on the research page.

The entire card is a link if the field has a value

![image.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/a66de099-f382-4bd4-aaf5-b322425b13f0)

**Comment by meeragovindaraju** [comment]
https://trello.com/c/FQzsnT1S/831-create-optional-links-on-current-projects-on-the-research-page

**Comment by mwharrison** [comment]
@RoyEJohnson - This needs some FE work. Moving to Selected column.

**Comment by Malar-Natarajan** [comment]
Verified in QA
