### ISSUE TITLE
Bug: should sign up be shown if logged in as an instructor?

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#71]
### **SCENARIO**
The Sign up link is present even after signing in / approved as a teacher. Should it be hidden if an instructor is signed in?

### **PROPOSED SOLUTION**
CMS currently has `free_stuff_instructor.content` with `heading` and `content`. It should also have a `sign_up` member, which will only be displayed if the user is not logged in as an instructor.

Add a new field in the CMS for logged in content and keep this one for non-logged in content. Implement on the FE.

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [ ] ` Tutor
` [ ] ` Highlight ` [X] ` Web
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [X] ` Teacher
` [ ] ` N/A

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

![image.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/3aec8569-4181-40d3-9bbf-da59981cd5bd)

**Comment by meeragovindaraju** [comment]
https://trello.com/c/2qsyDPpG/737-bug-should-sign-up-be-shown-if-logged-in-as-an-instructor

**Comment by Malar-Natarajan** [comment]
Verified in QA
