### ISSUE TITLE
Some blog images load very slowly outside the office

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#73]
### SCENARIO
Some blog images load very slowly. I noticed this while looking at the site from home. The main cause is the size of the images. The image linked below is 2.9MB and 2400px x 1200px which is large for a web image.

https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/original_images/alyssa-foley-blog-series.png

We need to determine a correct size for the images so all of them perform the same.

**Environment:**

- **Instance:**
` [X ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**

**Comment by meeragovindaraju** [comment]
https://trello.com/c/3uMGUO7b/621-some-blog-images-load-very-slowly-outside-the-office

**Comment by allisonhowell** [comment]
I am closing this because we have been able to make these images smaller. We'll revisit if this continues to be a problem.
