### ISSUE TITLE
Bug: the aria label for the 'subjects', 'technology' and 'what we do' nav menus  are all "Subjects menu"

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#75]
![image.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/048d3c14-ddab-43ef-bf5f-26744b1101ef)

**Comment by meeragovindaraju** [comment]
https://trello.com/c/TqENAKYj/915-bug-the-aria-label-for-the-subjects-technology-and-what-we-do-nav-menus-are-all-subjects-menu

**Comment by RoyEJohnson** [comment]
This is fixed here: https://github.com/openstax/os-webview/commit/6f0eb8cce9c16658fd7ce3f3856ea9b76c820d96

(The main PR is for the Creator Fest logo, but this was a trivial little change, so I just piggybacked it in.)

**Comment by Malar-Natarajan** [comment]
Verified in QA
