### ISSUE TITLE
Bug: seem to have lost the CogBooks logo on QA

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#76]
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [ ] ` Tutor
` [ ] ` Highlight ` [X] ` Web
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [X] ` N/A
- **Username:** 
- **URL:**  https://oscms-qa.openstax.org/details/books/biology?Instructor%20resources

![image.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/94daa5b0-686e-4eee-bef0-4cba40145e20)

![image.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/cb47f303-8596-47a8-b9be-cc86460cd3ff)

**Comment by meeragovindaraju** [comment]
https://trello.com/c/Id4l7hMS/916-bug-seem-to-have-lost-the-cogbooks-logo-on-qa

**Comment by allisonhowell** [comment]
This isn't on cms-qa or production, therefore, I'm closing.
