### ISSUE TITLE
Change errata to use user account data from accounts.openstax.org, instead of local CMS user accounts

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#85]
# Description
We are trying to remove the local user accounts from OSWeb. 
The errata application ties each erratum to a local user account.
We should change the way errata are tied to user accounts, by using an email address, uuid, accounts id, etc.

# Acceptance
Erratum are no longer tied to local CMS user accounts.

# Impact
* **Severity**: [ ] High [x] Medium  [ ] Low

**Comment by meeragovindaraju** [comment]
https://trello.com/c/8Bjx0JNi/844-change-errata-to-use-user-account-data-from-accountsopenstaxorg-instead-of-local-cms-user-accounts

**Comment by meeragovindaraju** [comment]
Released 10-22-2018

**Comment by allisonhowell** [comment]
@mwharrison Shouldn't this be closed?

**Comment by mwharrison** [comment]
@allisonhowell, per @meeragovindaraju's comment above, this was released on 10-22. I'm not sure what we are doing with cards that are released... but this should go in that place.
