### ISSUE TITLE
Add "Apple" before iBook in site comp copy

### ISSUE THREAD

**Issue by velcrohook02** [openstax/bit#87]
### Description
We need to add "Apple" before iBooks in the iBooks Comp Copy tile on the Instructor Resources tab.  Instructors often request them not realizing that they are Apple specific.  We believe iBook has become equivalent to e-book to many people.
----------------

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [X] ` Teacher
` [ ] ` N/A
----------------

- **Instance:**
` [X] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [X] ` Windows
` [X] ` Android ` [X] ` iOS
- **Browser:**
All

----------------
**Possible impact on a User:**
Instructor users receive a download code they can't use and CS wastes one of our limited number of codes.

----------------
**Images or Screenshots** 
![2018-10-25_09-45-34.png](https://images.zenhubusercontent.com/5bb524af9cd7cb7bbd9d0954/6e43c649-556c-4dbf-a2f7-33ede7d56627)

**Comment by bonnebbrown** [comment]
@meeragovindaraju

**Comment by allisonhowell** [comment]
Changed in CMS.
