### ISSUE TITLE
Integrate SSO between Accounts and Open edX platform

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/bit#88]
# Description
As an OpenStax account holder, I want to be able to use my OpenStax login credentials to access Rover by OpenStax, so that my transition to the product is easy, intuitive, and gives me the impression that I'm still within the OpenStax suite of products. 
 
# Acceptance Criteria
- OpenStax account holders experience a seamless handoff from OpenStax.org to Rover by OpenStax 
- OpenStax account holders can use their OpenStax login credentials to access and use Rover by OpenStax
- The Accounts process for Rover by OpenStax follows a similar pattern to the process in OpenStax Tutor

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
~~- [ ] If UX design is needed then the UX label is added~~
~~- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~~
~~- [ ] A high-level solution (development approach for the code change) is added to the issue~~
~~- [ ] If prototype code is generated, it is linked to the issue.~~
~~- [ ] If tech briefs are generated, they are linked to the issue.~~

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items.
- [x] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [x] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [x] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  ~~- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.~~
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

**Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by meeragovindaraju** [comment]
https://trello.com/c/XBOqWabj/921-integrate-sso-between-accounts-and-open-edx-platform

**Comment by allisonhowell** [comment]
Verified but waiting to move until Rover launches this week.
