### ISSUE TITLE
KD Develop OpenStax Impact (digital annual report) page

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#90]
### Description

We are turning the “Our Impact” page of openstax.org into our “digital annual report,” which will take key elements of the printed report and repurpose them for the website. This page will stay fresh and be updated frequently with correct numbers and impact statements. 

We must leverage the power of OpenStax.org and its millions of visitors to develop a culture of philanthropy. By capitalizing on the most visible product in our arsenal, we have the potential to catch the attention of the next foundation or individual that could greatly increase OpenStax’s impact. In addition, we want to inspire our visitors who may not be able to give financially, but who may be encouraged to give back in other ways.

Epic: https://docs.google.com/document/d/1tKiuOvB9pQTwWXdR8bY-n7uJSHS_Xg712ceEbihdpmk/edit#heading=h.wuc3pn1ckk21 

### Acceptance

There is a new page under "Our Impact" on OpenStax.org.

**Comment by allisonhowell** [comment]
@RoyEJohnson Here is the Invision link for this page: https://projects.invisionapp.com/share/5MHJ5EJH6J4#/screens/321961837

**Comment by RoyEJohnson** [comment]
@mwharrison This will require renaming the current impact slug to institutional-partners and creating a new impact page in the cms.

**Comment by allisonhowell** [comment]
@RoyEJohnson I did a UX review round 2 for this page since we have some more time. Just a few little things:

https://docs.google.com/document/d/1Z95NxjYTMXu_BYQcmIBIalZ2bPNkch1ipoiiEOtSzWs/edit

**Comment by RoyEJohnson** [comment]
You can see the updated version in Dev.
