### ISSUE TITLE
Longer Partner resource hover descriptions aren't contained in the box

### ISSUE THREAD

**Issue by gregfitch** [openstax/bit#92]
### Description

**SCENARIO** _Briefly describe the issue._

Partner resources with longer on-hover text run outside the box

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [X] ` N/A
- **Username:** 
- **URL:**  https://cms-qa.openstax.org/details/books/us-history?Partners
- **Course number:**  
- **Course type:**  

- **Steps**

Mouse over ExpertTA or Barnes&Noble Courseware

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [X] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

minimal
![screen shot 2018-10-29 at 2 32 28 pm](https://user-images.githubusercontent.com/8904283/47675538-3c63aa80-db88-11e8-8419-a738318b8d25.png)

----------------
**Images or Screenshots** (_attach below_)

**Comment by meeragovindaraju** [comment]
@allisonhowell Work is done!
