### ISSUE TITLE
Bug: Admins cannot mark users as test users

### ISSUE THREAD

**Issue by jessicatelles** [openstax/bit#99]
Trello: https://trello.com/c/1fB1ED2x/916-bug-admins-cannot-mark-users-as-test-users

**Scenario** Admins cannot mark users as test users in the admin console UI. The setting does not save properly.

This is in Accounts

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
` [X] ` Accounts ` [ ] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [ ] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
- **User Type:**
` [x] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [X] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [x] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [x] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

![Screen_Shot_2018-09-28_at_4.00.42_PM.png](https://images.zenhubusercontent.com/5b7582ca1006d675626d97f0/69fa65d9-dc6a-4e41-ba3f-4f4d4e490fc4)

**Comment by meeragovindaraju** [comment]
Duplicate issue
